// stubs/breeze/inertia-vue-ts/resources/js/Components/ConnectedAccount.vue
<script setup lang="ts">
import {computed, defineProps} from 'vue';
import ProviderIcon from '@/Components/SocialstreamIcons/ProviderIcon.vue';

const props = defineProps<{
    provider: string;
    createdAt?: string;
}>();

const providerName = computed(() => {
    switch (props.provider) {
        case 'twitter':
        case 'twitter-oauth-2':
            return 'Twitter';
        case 'linkedin':
        case 'linkedin-openid':
            return 'LinkedIn';
        default:
            return props.provider.charAt(0).toUpperCase() + props.provider?.slice(1);
    }
});
</script>

<template>
    <div>
        <div class="px-3 flex items-center justify-between">
            <div class="flex items-center">
                <ProviderIcon :provider="provider" classes="h-6 w-6 mr-2"/>

                <div>
                    <div class="text-sm font-semibold text-gray-600 dark:text-gray-400">
                        {{ providerName }}
                    </div>

                    <div v-if="createdAt !== null" class="text-xs text-gray-500">
                        Connected {{ createdAt }}
                    </div>

                    <div v-else class="text-xs text-gray-500">
                        Not connected.
                    </div>
                </div>
            </div>

            <slot name="action"></slot>
        </div>
    </div>
</template>

// stubs/breeze/inertia-react-ts/resources/js/Components/ConnectedAccount.tsx
import { PropsWithChildren } from 'react';
import ProviderIcon from '@/Components/SocialstreamIcons/ProviderIcon.jsx';
import { ConnectedAccount as ConnectedAccountType } from '@/types';

export default function ConnectedAccount({ children, provider, connectedAccount }: PropsWithChildren<{
    provider: string,
    connectedAccount?: ConnectedAccountType
}>) {
    const providerName = (): string => {
        switch(provider) {
            case 'twitter':
            case 'twitter-oauth-2':
                return 'Twitter'
            case 'linkedin':
            case 'linkedin-openid':
                return 'LinkedIn'
            default:
                return provider.charAt(0).toUpperCase() + provider?.slice(1);
        }
    }

    return (
        <div>
            <div className="px-3 flex items-center justify-between">
                <div className="flex items-center">
                    <ProviderIcon provider={provider} className="h-6 w-6"/>

                    <div className="ml-2">
                        <div className="text-sm font-semibold text-gray-600 dark:text-gray-400">
                            {providerName()}
                        </div>

                        {connectedAccount?.created_at ? (
                            <div className="text-xs text-gray-500">
                                Connected {connectedAccount.created_at}
                            </div>
                        ) : (
                            <div className="text-xs text-gray-500">
                                Not connected.
                            </div>
                        )}
                    </div>
                </div>

                {children}
            </div>
        </div>
    )
}
