// stubs/breeze/inertia-vue/resources/js/Components/ConnectedAccount.vue
<script setup>
import {computed, defineProps} from 'vue';
import ProviderIcon from '@/Components/SocialstreamIcons/ProviderIcon.vue';

const props = defineProps({
    provider: {
        type: Object
    },
    createdAt: {
        type: String,
        default: null,
    }
});
</script>

<template>
    <div>
        <div class="px-3 flex items-center justify-between">
            <div class="flex items-center">
                <ProviderIcon :provider="provider" classes="h-6 w-6 me-2"/>

                <div class="ms-2">
                    <div class="text-sm font-semibold text-gray-600 dark:text-gray-400">
                        {{ provider.name }}
                    </div>

                    <div v-if="createdAt !== null" class="text-xs text-gray-500">
                        Connected {{ createdAt }}
                    </div>

                    <div v-else class="text-xs text-gray-500">
                        Not connected.
                    </div>
                </div>
            </div>

            <slot name="action"></slot>
        </div>
    </div>
</template>

// stubs/breeze/inertia-react/resources/js/Components/ConnectedAccount.jsx
import ProviderIcon from '@/Components/SocialstreamIcons/ProviderIcon.jsx';

export default function ConnectedAccount({ children, provider, connectedAccount }) {
    return (
        <div>
            <div className="px-3 flex items-center justify-between">
                <div className="flex items-center">
                    <ProviderIcon provider={provider} className="h-6 w-6" />

                    <div className="ml-2">
                        <div className="text-sm font-semibold text-gray-600 dark:text-gray-400">{provider.name}</div>

                        {connectedAccount?.created_at ? (
                            <div className="text-xs text-gray-500">Connected {connectedAccount.created_at}</div>
                        ) : (
                            <div className="text-xs text-gray-500">Not connected.</div>
                        )}
                    </div>
                </div>

                {children}
            </div>
        </div>
    );
}
