// stubs/breeze/inertia-react/resources/js/Components/ActionLink.jsx
export default function ActionLink({ className = '', href, children, ...props }) {
    return (
        <a
            {...props}
            href={href}
            className="inline-flex items-center px-4 py-2 bg-white border border-gray-800 rounded-md font-semibold text-xs text-gray-800 uppercase tracking-widest hover:bg-gray-200 hover:border-gray-600 active:border-gray-900 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150"
        >
            {children}
        </a>
    );
}

// stubs/breeze/inertia-vue-ts/resources/js/Components/ActionLink.vue
<script setup lang="ts">
defineProps<{
    href: string;
}>();
</script>

<template>
    <a :href="href"
       class="inline-flex items-center px-4 py-2 bg-white border border-gray-800 rounded-md font-semibold text-xs text-gray-800 uppercase tracking-widest hover:bg-gray-200 hover:border-gray-600 active:border-gray-900 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">
        <slot></slot>
    </a>
</template>
